name: Build

on:
  workflow_call:

env:
  EMACS_VERSION: 29.1
  HUGO_VERSION: 0.130.0
  NODE_VERSION: 20

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
          submodules: recursive

      - name: Set up Emacs ${{ env.EMACS_VERSION }}
        uses: purcell/setup-emacs@master
        with:
          version: ${{ env.EMACS_VERSION }}
      - name: Cache Emacs packages
        uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4
        with:
          path: content-org/.packages
          key: ${{ runner.os }}-emacs-${{ hashFiles('content-org/export.el') }}

      - name: Set up Hugo ${{ env.HUGO_VERSION }}
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
      - name: Set up Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --prod

      - name: Build content
        run: |
          cd content-org
          ./export.el 'notes/*.org'
      - name: Build website
        run: |
          pnpm build \
            --baseURL "$BASE_URL" \
            --destination "public"
          make compress
        env:
          BASE_URL: ${{ github.event_name == 'pull_request' && 'https://dev.notes.unindented.org/' || 'https://notes.unindented.org/' }}

      - name: Upload website
        uses: actions/upload-artifact@604373da6381bf24206979c74d06a550515601b9 # v4
        with:
          name: website
          path: public
          retention-days: 1
