name: Test

on:
  workflow_call:

env:
  NODE_VERSION: 20

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.45.1-jammy
    env:
      HOME: /root
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
          submodules: recursive

      - name: Download website
        uses: actions/download-artifact@v4
        with:
          name: website
          path: public

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
      - name: Set up Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright browsers
        run: pnpm playwright install

      - name: Run lint tests
        run: pnpm test:lint
      - name: Run type checks
        run: pnpm test:type
      - name: Run e2e tests
        run: pnpm test:e2e

      - name: Upload e2e test reports
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: e2e-reports
          path: |
            e2e-report/
            e2e-results/
          retention-days: 3

  lhci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
          submodules: recursive

      - name: Download website
        uses: actions/download-artifact@v4
        with:
          name: website
          path: public

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
      - name: Set up Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Run Lighthouse tests
        run: pnpm test:lhci
